import "./globals.css";
import Navigation from "./components/layout/navigation";
import Footer from "./components/common/button/footer/Footer";
import { Metadata } from "next";
import { Montserrat } from "next/font/google";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={montserrat.className}> 
        <Navigation />
        <main>{children}</main>
        <Footer />
        <footer className="bg-secondary text-white p-4 text-center">
          <p>&copy; {new Date().getFullYear()} Lost Key. All rights reserved.</p>
        </footer>
      </body>
    </html>
  );
}
